MySql/Models/Bowler.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MySql.Models
{
    public class Bowler
    {
        [Key]
        [Required]
        public int BowlerID { get; set; }

        public string BowlerLastName { get; set; }

        public string BowlerFirstName { get; set; }

        public string BowlerMiddleInit { get; set; }

        public string BowlerAddress { get; set; }

        public string BowlerCity { get; set; }

        public string BowlerState { get; set; }

        public string BowlerZip { get; set; }

        public string BowlerPhoneNumber { get; set; }



        //Build foreign Key Relationship

        public int TeamID { get; set; }

        public Team TeamName { get; set; }

    }
}

MySql/Models/BowlingDbContext.cs
using System;
using Microsoft.EntityFrameworkCore;

namespace MySql.Models
{
    public class BowlingDbContext : DbContext
    {

        public BowlingDbContext(DbContextOptions<BowlingDbContext> options) : base(options)
        {

        }

        public DbSet<Bowler> Bowlers { get; set; }
        public DbSet<Team> Teams { get; set; }
    }
}

MySql/Models/EFBowlersRepository.cs
using System;
using System.Linq;

namespace MySql.Models
{
    public class EFBowlersRepository : IBowlersRepository
    {
        private BowlingDbContext _context { get; set; }

        public EFBowlersRepository(BowlingDbContext temp)
        {
            _context = temp;

        }

        public IQueryable<Bowler> Bowlers => _context.Bowlers;
        
    }
}

MySql/Models/EFTeamsRepository.cs
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace MySql.Models
{
    public class EFTeamsRepository : ITeamsRepository
    {
        private BowlingDbContext _context { get; set; }

        public EFTeamsRepository (BowlingDbContext temp)
        {
            _context = temp;
        }

        public IQueryable<Team> Teams => _context.Teams.Include(x => x.TeamName);
    }
}

MySql/Models/IBowlersRepository.cs
using System;
using System.Linq;

namespace MySql.Models
{
    public interface IBowlersRepository
    {
        IQueryable<Bowler> Bowlers { get; }


    }
}

MySql/Models/ITeamsRepository.cs
using System;
using System.Linq;

namespace MySql.Models
{
    public interface ITeamsRepository
    {
        IQueryable<Team> Teams { get;  }
    }
}

MySql/Models/Team.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MySql.Models
{

    public class Team
    {
        [Key]
        [Required]
        public int TeamID { get; set; }

        [Required]
        public string TeamName { get; set; }

        [Required]
        public int CaptainID { get; set; }

    }
}

MySql/Components/TeamsMenuViewComponent.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MySql.Models;

namespace MySql.Components
{
    public class TeamsMenuViewComponent : ViewComponent
    {
        private IBowlersRepository repo { get; set; }

        public TeamsMenuViewComponent (IBowlersRepository temp)
        {
            repo = temp;
        }
        
        public IViewComponentResult Invoke()
        {
            ViewBag.TeamName = RouteData?.Values["TeamName"];

            var teams = repo.Bowlers.Select(x => x.TeamName.TeamName).Distinct().OrderBy(x => x);
            return View(teams);
        }
    }
}

MySql/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MySql.Models;
//using MySql.Models;

namespace MySql.Controllers
{
    public class HomeController : Controller
    {
        private BowlingDbContext _repo { get; set; }

        //constructor
        public HomeController(BowlingDbContext temp)
        {
            _repo = temp;
        }


        public IActionResult Index(string teamName)
        {
            ViewBag.name = RouteData?.Values["teamName"];

            List<Team> teams = _repo.Teams
                .Where(x => x.TeamName == teamName || teamName == null)
                .ToList();

            List<Bowler> bowlers = _repo.Bowlers
                .Where(x => x.TeamName.TeamName == teamName || teamName == null)
                .OrderBy(x => x.BowlerID)
                .ToList();
            return View(bowlers);
        }

        [HttpGet]
        public IActionResult NewBowler()
        {
            ViewBag.Teams = _repo.Teams.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult NewBowler(Bowler ar)
        {
            _repo.Add(ar);
            _repo.SaveChanges();

            return View("Confirmation", ar);
        }

        [HttpGet]
        public IActionResult Edit(int bowlerid)
        {
            ViewBag.Bowler = _repo.Bowlers.ToList();

            var application = _repo.Bowlers.Single(x => x.BowlerID == bowlerid);

            return View("NewBowler", application);
        }
        [HttpPost]
        public IActionResult Edit(Bowler mv)
        {
            _repo.Update(mv);
            _repo.SaveChanges();

            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Delete(int applicationid)
        {

            var application = _repo.Bowlers.Single(x => x.BowlerID == applicationid);

            return View(application);
        }
        [HttpPost]
        public IActionResult Delete(Bowler mv)
        {
            _repo.Bowlers.Remove(mv);
            _repo.SaveChanges();

            return RedirectToAction("Index");
        }
    }


}

MySql/Views/Home/Confirmation.cshtml
@{
    ViewData["Title"] = "Bowler added";
}

@model MySql.Models.Bowler

<h2> Bowler @Model.BowlerFirstName added! </h2>

MySql/Views/Home/Delete.cshtml
@{
}
@model Bowler


<h2> Confirm Deletion </h2>
<h3> Are you sure you want to delete the record for @Model.BowlerFirstName?</h3>

<form method="post" asp-controller="Home" asp-action="Delete">
    <button type="submit">Delete</button>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Cancel </a>

    <input type="hidden" asp-for="BowlerID" />


</form>

MySql/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<h1>@ViewBag.name</h1>
@model List<Bowler>

<div>
    <a asp-controller="Home" asp-action="NewBowler"> New Bowler </a>
</div>

<table class="table table-bordered table-striped">

    <thead class="font-weight-bold">
        <tr>

            <td>Bowler Lastname: </td>
            <td>Bowler Firstname: </td>
            <td>Bowler MiddleInit: </td>
            <td>Bowler Address: </td>
            <td>Bowler City: </td>
            <td>Bowler State: </td>
            <td>Bowler Zip: </td>
            <td>Bowler Phone Number: </td>
            <td>TeamID: </td>
            <td>BowlerID: </td>
            @*<td>TeamName: </td>*@

        </tr>
    </thead>

    <tbody>

        @foreach (var x in Model)
        {
        <tr>

            <td>@x.BowlerLastName </td>
            <td>@x.BowlerFirstName </td>
            <td>@x.BowlerMiddleInit </td>
            <td>@x.BowlerAddress </td>
            <td>@x.BowlerCity </td>
            <td>@x.BowlerState </td>
            <td>@x.BowlerZip </td>
            <td>@x.BowlerPhoneNumber </td>
            <td>@x.TeamID</td>
            <td>@x.BowlerID</td>
            @*<td>@x.TeamName.TeamName</td>*@


                <td><a asp-controller="Home" asp-action="Edit" asp-route-bowlerid="@x.BowlerID">Edit</a></td>
            <td><a asp-controller="Home" asp-action="Delete" asp-route-applicationid="@x.BowlerID">Delete</a></td>

        </tr>

        }


    </tbody>
</table>

MySql/Views/Home/NewBowler.cshtml
@{
    ViewData["Title"] = "Add Bowler";
}

@model MySql.Models.Bowler


<h1> Add new bowler </h1>

<div>
    <form method="post">

        <label asp-for="BowlerLastName"> Last Name: </label>
        <input asp-for="BowlerLastName" /> <br />

        <label asp-for="BowlerFirstName"> First Name: </label>
        <input asp-for="BowlerFirstName" /> <br />


        <label asp-for="BowlerMiddleInit"> Bowler Middle Init: </label>
        <input asp-for="BowlerMiddleInit" /> <br />

        <label asp-for="BowlerAddress"> Address: </label>
        <input asp-for="BowlerAddress" /> <br />

        <label asp-for="BowlerCity"> City: </label>
        <input asp-for="BowlerCity" /> <br />

        <label asp-for="BowlerState"> State:  </label>
        <input asp-for="BowlerState" /> <br />

        <label asp-for="BowlerZip"> Zip </label>
        <input asp-for="BowlerZip" /> <br />

        <label asp-for="BowlerPhoneNumber"> Phone: </label>
        <input asp-for="BowlerPhoneNumber" /> <br />


        <label asp-for="TeamID "> TeamID : </label>
        <input asp-for="TeamID " /> <br />



        <button type="submit"> Submit Application</button>
    </form>


</div>

MySql/Views/Shared/Components/TeamsMenu/Default.cshtml
@{
}
@model IEnumerable<string>
<a class="btn btn-block btn-outline-secondary" asp-controller="Home" asp-action="Index" asp-route-teamName=""> Home </a>

@foreach (string t in Model)
            {
                <a class="btn btn-block
       @(t == ViewBag.TeamName ? "btn-primary": "btn-outline-secondary")" asp-controller="Home" asp-action="Index" asp-route-teamName="@t">@t</a>
            }

MySql/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bowlers </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MySql</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div class="row">
            <div id="teamName" class="col-3">
                <vc:teams-menu></vc:teams-menu>
            </div>
            <main role="main" class="col-9">
                @RenderBody()
            </main>
        </div>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MySql - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>